### ISSUE TITLE
Initial admin role id issue

### ISSUE THREAD

**Issue by Blaxzter** [bcc-code/directus-schema-sync#35]
### Describe the Bug

I added directus-schema-sync to a local directus with docker once on my laptop and once in a new directus docker environment on my main pc.
I used the same env parameter in both installs (both host systems are windows 11). 

I set the env SCHEMA_SYNC: "BOTH" but there was no automatic schema sync in directus.
After that I run `docker-compose exec -it directus npx directus schema-sync import` which run through and after a refresh in the browser I was greeted with "user doesn't has app access" which was the admin user. 

![image](https://github.com/bcc-code/directus-schema-sync/assets/9212841/2e0ab267-e1c6-4d92-88f6-f3591253ff33)

This is the role diff after I killed the directus docker image / volumes, recreated the roles manually and exported again.
Could it be the reason that a user has a role id assigned and overwriting these roles with a new one removes the association?

### To Reproduce

Setup two directus instances.
Export/Import from A to B and refresh.

(I have not verified that again 😅)

### Version

1.6.4

### Installed Extension Via

Docker file

**Comment by u12206050** [comment]
Hmm, I see you are exporting the role id so it should be correctly synced and not be creating "duplicates".
But since you say " recreated the roles manually " then that of course will create new roles with new ids, so you should rather be just importing your current configuration after starting up a fresh docker container in order to get the same roles with same id.
