### ISSUE TITLE
Add a Query Rule to directus_roles

### ISSUE THREAD

**Issue by wolfgang-hartl** [bcc-code/directus-schema-sync#44]
### Describe the Improvement

Hey there, not sure if this was already considered in the past, but when using the extension I find my self needing to do a little tweak all the time, it's not a big deal since one have to modify the config file anyway, but I think it would be a good addition to the starter to exclude the "Administrator" Role from syncing, found myself often locked out of directus because it synced and lost the relation to the admin user because of that. 

<img width="471" alt="image" src="https://github.com/bcc-code/directus-schema-sync/assets/75800215/c6ae2804-0c65-4051-85bf-ab17734789d3">

As far as I can see, it's located in the install/schema-sync folder of the project (not sure if i should open a pull request for that minor change, and if it's even wanted to be that way). 

Thanks for considering, and thanks for the awesome extension, works really great!! :-) 

Cheers

**Comment by u12206050** [comment]
Hi, thanks for your input. We have actually considered this already and it turns out there are people on both sides of the isle on this one. So in the spirit of sitting on the fence I decided to just not include to much default filter rules, and let those that don't want it exclude it like you have done so yourself.

Once excluding the Admin role becomes 80% of the use cases we can change it, but as of now it is 50/50
